schema_version: 1

context:
  version: 1.154.0

package:
  name: aws-sam-cli
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/aws-sam-cli/aws_sam_cli-${{ version }}.tar.gz
  sha256: 4f3cb8781c1873028111d8e614f731b039d6095fa683a9b71e9d110070d0870e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sam=samcli.cli.main:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - chevron >=0.12,<1.dev0
    - click ==8.1.8
    - flask <3.2
    - boto3 ==1.42.26
    - jmespath >=1.0.1,<1.1.dev0
    - ruamel_yaml >=0.18.16,<0.19.dev0
    - pyyaml >=6.0,<7.dev0
    - cookiecutter >=2.6.0,<2.7.dev0
    - aws-sam-translator ==1.107.0
    - docker-py >=7.1.0,<7.2.dev0
    - dateparser >=1.2,<2.dev0
    - requests >=2.32.5,<2.33.dev0
    - aws_lambda_builders ==1.62.0
    - tomlkit ==0.14.0
    - watchdog ==4.0.2
    - rich >=14.2.0,<14.3.dev0
    - pyopenssl >=25.3.0,<25.4.dev0
    - jsonschema <4.27
    - typing_extensions >=4.4.0,<5
    - regex !=2021.10.8
    - tzlocal ==5.3.1
    - cfn-lint >=1.43.1,<1.44.dev0
    - boto3-stubs >=1.41.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - samcli
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - sam --help

about:
  summary: AWS SAM CLI is a CLI tool for local development and testing of Serverless applications
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - NOTICE
    - samcli/lib/init/templates/cookiecutter-aws-sam-hello-java-maven/LICENSE
    - samcli/lib/init/templates/cookiecutter-aws-sam-hello-nodejs/LICENSE
    - samcli/lib/init/templates/cookiecutter-aws-sam-hello-java-gradle/LICENSE
    - samcli/lib/init/templates/cookiecutter-aws-sam-hello-python/LICENSE
    - samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/LICENSE
    - samcli/lib/init/templates/cookiecutter-aws-sam-hello-ruby/LICENSE
  homepage: https://github.com/aws/aws-sam-cli

extra:
  recipe-maintainers:
    - mxr-conda
    - achangeo
    - oblute
    - xhochy
